In [17]:
import random
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import copy

from dqn import Environment, DQNAgent

In [59]:
env = Environment(num_players=3)
env.reset()

# Initialize DQN agent.
state_size = env.state_size
action_size = env.num_actions
agent = DQNAgent(state_size, action_size)

agent.load('trained.model')

In [78]:
test_state = np.reshape(np.array([0,0,1,0,0,0]), (1,6))

In [79]:
agent.model.predict(test_state)

array([[ 0.40762836, -0.39025888, -2.165325  ]], dtype=float32)

In [108]:
agent.load('trained_len3.model')

In [113]:
test_state = np.reshape(np.array([0,0,1,0,0,0]), (1,6))

In [114]:
agent.model.predict(test_state)

array([[-2.7672195, -2.6553907, -2.6042368]], dtype=float32)

In [152]:
agent.load('trained_len3_w10_e200.model')

In [159]:
test_state = np.reshape(np.array([0,1,1,0,1,0]), (1,6))

In [160]:
agent.model.predict(test_state)

array([[-1.0001947, -2.1183486, -3.0007298]], dtype=float32)

In [ ]:
0 = (0,0,1,0,0,0)
1 = (0,1,1,0,0,0)
2 = (1,0,1,1,0,0)
3 = (1,1,1,1,0,0)
4 = (0,0,2,0,0,0)
5 = (0,0,2,0,0,1)
6 = (0,1,2,0,0,0)
7 = (0,1,2,0,0,1)
8 = (1,0,2,1,0,0)
9 = (1,0,2,1,0,1)
0 = (1,1,2,1,0,0)
1 = (1,1,2,1,0,1)
2 = (0,2,1,0,0,0)
3 = (1,2,1,1,0,0)
4 = (2,0,1,2,0,0)
5 = (2,1,1,2,0,0)